### ISSUE TITLE
if you wanth to add my so i can help

### ISSUE THREAD

**Issue by caspervanneck** [PikyCZ/MobPlugin#2]
👍 👍 👍 👍 👍

**Comment by Creeperface01** [comment]
but circle CI is still broken :/ nukkit dependency

**Comment by NycuRO** [comment]
@Creeperface01 Add me collaborator. I can fix .

**Comment by PikyCZ** [comment]
wait

**Comment by NycuRO** [comment]
@caspervanneck @Creeperface01 @PikyCZ CircleCI fixed

**Comment by PikyCZ** [comment]
Ok thanks  :)

**Comment by caspervanneck** [comment]
@PikyCZ  wgy am y no collaborator ?
