### ISSUE TITLE
Wtf?

### ISSUE THREAD

**Issue by NycuRO** [PikyCZ/MobPlugin#34]
@PikyCZ Why you removed me and @Creeperface01 from collaboration? 👎

**Comment by PikyCZ** [comment]
You no longer work on mobplugin

**Comment by NycuRO** [comment]
@PikyCZ LOL, you're noob. If one person not work for you, need to delete.

Creeper helped you and you deleted from project, dude.

Fucking person.

**Comment by PikyCZ** [comment]
...

**Comment by PikyCZ** [comment]
you .. :D
