### ISSUE TITLE
Server crashes when a mob spawns

### ISSUE THREAD

**Issue by DxDen1004** [PikyCZ/MobPlugin#41]
Since Nukkit doesn't handle mobs AI, I decided to try your plugin. Anyway, when the first mob spawned, it started glitching in a very weird way, then the server crashed returning this log:
[2017-5-30 16.46.55.txt](https://github.com/PikyCZ/MobPlugin/files/1038699/2017-5-30.16.46.55.txt)

Hope you can figure out what's causing the issue. I'm using the last release of Nukkit (#599).

Thanks, Den.

**Comment by Creeperface01** [comment]
Use circle CI

**Comment by DxDen1004** [comment]
Thank you!
