### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by Black-Bass** [PikyCZ/MobPlugin#43]
Is there a tutorial with commands and plugin settings? For example, how works auto spawning?

**Comment by DxDen1004** [comment]
Actually using this plugin mobs are not spawning in the world. I have to manually spawn them using eggs or spawners. I don't know if there is a setting to allow them to spawn automatically

**Comment by Creeperface01** [comment]
They should spawn automatically

**Comment by Black-Bass** [comment]
Never seen it automatically spawned mobs. To create a mob, i have to use the command /mob spawn <mob>

**Comment by Black-Bass** [comment]
Up. What to do if the mobs do not spawn automatically? Maybe they are few? How to increase their number? Thanks for your work.

**Comment by PikyCZ** [comment]
AutoSpawning do not working..
