### ISSUE TITLE
List of Issues

### ISSUE THREAD

**Issue by PikyCZ** [PikyCZ/MobPlugin#44]
- [x]  Create Wiky (#38)
- [x]  Fix Commands (#42)

**Comment by PikyCZ** [comment]
https://github.com/PikyCZ/MobPlugin/pull/45

**Comment by vzlomka76** [comment]
@PikyCZ very high load on the server (sorry for my bad English)
When online in 1 player, the load reaches 50%, or even 100%.

**Comment by PikyCZ** [comment]
In mobplugin 1.1 high load is fixed
![2017-06-06 6](https://user-images.githubusercontent.com/19613582/27004885-28771c50-4e12-11e7-88bd-8e2746d22838.png)

**Comment by vzlomka76** [comment]
@PikyCZ 43%? It's very high load

**Comment by PikyCZ** [comment]
![2017-06-10 1](https://user-images.githubusercontent.com/19613582/27005257-cbdfc3e4-4e1a-11e7-934e-7fd0f24eede7.png)

**Comment by PikyCZ** [comment]
i don´t know how to fix high load :/
