### ISSUE TITLE
plugin

### ISSUE THREAD

**Issue by alexbgameson** [PikyCZ/MobPlugin#46]
Please create new release

**Comment by PikyCZ** [comment]
Yep .. please wait 2-3days? ..

**Comment by PikyCZ** [comment]
Now i trying to rewrite plugin for new AIsystem(by creeperface) and this operation is so long :/

**Comment by PikyCZ** [comment]
@alexbgameson download from circleci ->
https://circleci.com/gh/PikyCZ/MobPlugin/323#artifacts/containers/0
