### ISSUE TITLE
#313 PlayerInteractEvent error

### ISSUE THREAD

**Issue by Jian-Ge** [PikyCZ/MobPlugin#47]
When I trigger InteraceEvent, the console is error with "Caused by: java.lang.NoSuchMethodError: cn.nukkit.event.player.PlayerInteractEvent.getAction () I
 at com.pikycz.mobplugin.MobPlugin.PlayerInteractEvent(MobPlugin.java:294)
"
My English is not very good, I hope you can understand what I mean. :p

**Comment by PikyCZ** [comment]
i know about this error .. :P
