### ISSUE TITLE
No config.yml, no autospawning

### ISSUE THREAD

**Issue by PetteriM1** [PikyCZ/MobPlugin#52]
Can you give me the config.yml file?

**Comment by PikyCZ** [comment]
im delete config,autospawn ..

**Comment by PetteriM1** [comment]
So is there config file anymore and if no why no mobs?

**Comment by asyven** [comment]
@PetteriM1 you need improve plugin for autospawn,
Turn autospawn listener in pluginbase  and change some code for correctry work

**Comment by PikyCZ** [comment]
-_-...

**Comment by rakesh37187** [comment]
I'm sorry I don't quite get what you mean. Why is there no auto-spawn? It seems rather useless to have a mobplugin without auto-spawn.

**Comment by PetteriM1** [comment]
I use release 1.1 and there is no autospawning. Should there be config.yml anymore?

**Comment by PetteriM1** [comment]
And why CircleCI build failing?

**Comment by Asuna-Yuuki** [comment]
@PetteriM1 because of Dependencies of maven

**Comment by PikyCZ** [comment]
Ok i create new Issue
