### ISSUE TITLE
almost compiling only code erors

### ISSUE THREAD

**Issue by Asuna-Yuuki** [PikyCZ/MobPlugin#58]
its almost compiling only code erors @PikyCZ your a java guy am not going to touch that if you can help it wil be great

**Comment by Asuna-Yuuki** [comment]
fixt its working

**Comment by PikyCZ** [comment]
I know .. i fix errors in code today

**Comment by Asuna-Yuuki** [comment]
@PikyCZ it's fix but I leave you alone because you blame me well..

**Comment by PikyCZ** [comment]
:D sorry .. you doing good work

**Comment by Asuna-Yuuki** [comment]
O ok

**Comment by PikyCZ** [comment]
Yea .. wee need chat :P

**Comment by Asuna-Yuuki** [comment]
@PikyCZ  discord?

**Comment by PikyCZ** [comment]
@Asuna-Yuuki  PikyCZ/#0714
