### ISSUE TITLE
Why mobs are deleted?

### ISSUE THREAD

**Issue by wbzhang2594** [PikyCZ/MobPlugin#72]
@PikyCZ , In this 3 months I saw you deleted so much files. Why?

This is the only nukkit plugin that can create mobs. I really wish you can go on with this great project.

**Comment by PikyCZ** [comment]
I remove unused mobs..  and autospawn since update 1.1 is broken .. yu can look to branch ReCreate and yu can help me ..

**Comment by PikyCZ** [comment]
@wbzhang2594

**Comment by wbzhang2594** [comment]
Would you share some detail of what you said "broken"?

And what's your plan?

**Comment by PikyCZ** [comment]
autospawn do not spawn mobs.. and my plan? .. create working config and autospawn .. (now)
