### ISSUE TITLE
Entities don't move.

### ISSUE THREAD

**Issue by OverTook** [PikyCZ/MobPlugin#9]
Their entities not only don't active but also when I hit them, they knockback until they reach wall.

Is it bug? Or my fault?

Nukkit : 544
Client : Android 1.0.0.16
Host OS : Windows 10 Redstone

**Comment by PikyCZ** [comment]
now i uplouad better version to Target Folder

**Comment by PikyCZ** [comment]
Use version from TargetFolder..

**Comment by Creeperface01** [comment]
how to reproduce? entities move normally for me

**Comment by OverTook** [comment]
@Creeferface01

I don't know. I just put the plugin in the folder. Then, just happend LOL.

**Comment by PikyCZ** [comment]
In latest builds entities move
